name: CI - Docker Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: |
          docker compose \
            -f .devcontainer/docker-compose.yml \
            build
      
      - name: Run CI test
        run: |
          docker compose \
            -f .devcontainer/docker-compose.yml \
            run --rm playwright-node \
            pytest
      
      - name: Cleanup
        if: always()
        run: |
          docker compose \
            -f .devcontainer/docker-compose.yml \
            down
